In [35]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [64]:
Data = pd.read_excel('heart_disease.xlsx', sheet_name ='Heart_disease')

In [65]:
Data.head(5)

age   sex               cp  trestbps  chol    fbs         restecg  thalch  \
0   63  Male   typical angina       145   233   True  lv hypertrophy     150   
1   41  Male  atypical angina       135   203  False          normal     132   
2   57  Male     asymptomatic       140   192  False          normal     148   
3   52  Male   typical angina       118   186  False  lv hypertrophy     190   
4   57  Male     asymptomatic       110   201  False          normal     126   

   exang  oldpeak        slope          thal  num  
0  False      2.3  downsloping  fixed defect    0  
1  False      0.0         flat  fixed defect    0  
2  False      0.4         flat  fixed defect    0  
3  False      0.0         flat  fixed defect    0  
4   True      1.5         flat  fixed defect    0

In [67]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       908 non-null    int64  
 1   sex       908 non-null    object 
 2   cp        908 non-null    object 
 3   trestbps  908 non-null    int64  
 4   chol      908 non-null    int64  
 5   fbs       908 non-null    bool   
 6   restecg   908 non-null    object 
 7   thalch    908 non-null    int64  
 8   exang     908 non-null    bool   
 9   oldpeak   908 non-null    float64
 10  slope     908 non-null    object 
 11  thal      908 non-null    object 
 12  num       908 non-null    int64  
dtypes: bool(2), float64(1), int64(5), object(5)
memory usage: 79.9+ KB


In [66]:
Data = Data.fillna(0)

In [68]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       908 non-null    int64  
 1   sex       908 non-null    object 
 2   cp        908 non-null    object 
 3   trestbps  908 non-null    int64  
 4   chol      908 non-null    int64  
 5   fbs       908 non-null    bool   
 6   restecg   908 non-null    object 
 7   thalch    908 non-null    int64  
 8   exang     908 non-null    bool   
 9   oldpeak   908 non-null    float64
 10  slope     908 non-null    object 
 11  thal      908 non-null    object 
 12  num       908 non-null    int64  
dtypes: bool(2), float64(1), int64(5), object(5)
memory usage: 79.9+ KB


In [58]:
Data['num'].value_counts()

num
0    399
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [59]:
Data['sex'].value_counts()

sex
Male      718
Female    190
Name: count, dtype: int64

In [60]:
Data['cp'].value_counts()

cp
asymptomatic       495
non-anginal        203
atypical angina    165
typical angina      45
Name: count, dtype: int64

In [61]:
Data['fbs'].value_counts()

fbs
False    723
True     185
Name: count, dtype: int64

In [62]:
Data['restecg'].value_counts()

restecg
normal              542
lv hypertrophy      187
st-t abnormality    179
Name: count, dtype: int64

In [69]:
Data['exang'].value_counts()

exang
False    536
True     372
Name: count, dtype: int64

In [70]:
label_encoder = LabelEncoder()
Data['restecg'] = label_encoder.fit_transform(Data['restecg'])
Data['sex'] = label_encoder.fit_transform(Data['sex'])
Data['cp'] = label_encoder.fit_transform(Data['cp'])
Data['fbs'] = label_encoder.fit_transform(Data['fbs'])
Data['exang'] = label_encoder.fit_transform(Data['exang'])
Data['slope'] = label_encoder.fit_transform(Data['slope'])
Data['thal'] = label_encoder.fit_transform(Data['thal'])

In [71]:
Data

age  sex  cp  trestbps  chol  fbs  restecg  thalch  exang  oldpeak  \
0     63    1   3       145   233    1        0     150      0      2.3   
1     41    1   1       135   203    0        1     132      0      0.0   
2     57    1   0       140   192    0        1     148      0      0.4   
3     52    1   3       118   186    0        0     190      0      0.0   
4     57    1   0       110   201    0        1     126      1      1.5   
..   ...  ...  ..       ...   ...  ...      ...     ...    ...      ...   
903   53    1   0       125     0    0        1     120      0      1.5   
904   62    1   0       166   170    0        2     120      1      3.0   
905   56    1   2       170     0    0        0     123      1      2.5   
906   56    1   2       144   208    1        2     105      1      0.0   
907   57    1   0       142   277    1        2     182      0      0.0   

     slope  thal  num  
0        0     0    0  
1        1     0    0  
2        1     0    0  
3        1     0    0  
4        1     0    0  
..     ...   ...  ...  
903      2     0    4  
904      1     2    4  
905      0     0    4  
906      0     0    4  
907      1     2    4  

[908 rows x 13 columns]

In [72]:
X=Data.iloc[:,0:10]
Y=Data['num']

In [73]:
X


age  sex  cp  trestbps  chol  fbs  restecg  thalch  exang  oldpeak
0     63    1   3       145   233    1        0     150      0      2.3
1     41    1   1       135   203    0        1     132      0      0.0
2     57    1   0       140   192    0        1     148      0      0.4
3     52    1   3       118   186    0        0     190      0      0.0
4     57    1   0       110   201    0        1     126      1      1.5
..   ...  ...  ..       ...   ...  ...      ...     ...    ...      ...
903   53    1   0       125     0    0        1     120      0      1.5
904   62    1   0       166   170    0        2     120      1      3.0
905   56    1   2       170     0    0        0     123      1      2.5
906   56    1   2       144   208    1        2     105      1      0.0
907   57    1   0       142   277    1        2     182      0      0.0

[908 rows x 10 columns]

In [74]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
903    4
904    4
905    4
906    4
907    4
Name: num, Length: 908, dtype: int64

In [75]:
# Splitting data into training and testing data set
x_train, x_test,y_train,y_test = train_test_split(X,Y, test_size=0.2,random_state=2023)
x_train.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalch  exang  oldpeak
295   54    0   1       120   230    1        1     140      0      0.0
760   51    0   0       120     0    1        1     127      1      1.5
301   41    1   0       112   250    0        1     142      0      0.0
428   59    1   3       160   273    0        0     125      0      0.0
68    65    0   2       160   360    0        0     151      0      0.8

In [76]:
y_train

295    0
760    2
301    0
428    1
68     0
      ..
732    2
695    2
454    1
537    1
855    3
Name: num, Length: 726, dtype: int64

In [77]:
#Building Decision Tree Classifier using Entropy Criteria
model = DecisionTreeClassifier(criterion = 'entropy', max_depth =None)
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [80]:
#PLot the decision tree
plt.figure(dpi=2000)
tree.plot_tree(model);

In [81]:
#Predicting on test data
preds = model.predict(x_test) # predicting on test data set 
# pd.Series(preds).value_counts() # getting the count of each category 
preds

array([2, 1, 0, 0, 0, 3, 0, 0, 0, 1, 0, 3, 3, 1, 0, 1, 2, 1, 1, 1, 0, 0,
       2, 1, 1, 0, 3, 0, 0, 0, 1, 1, 0, 1, 0, 0, 4, 0, 2, 1, 1, 0, 2, 0,
       2, 2, 2, 0, 0, 1, 0, 1, 3, 0, 0, 1, 3, 3, 1, 1, 0, 1, 2, 1, 3, 1,
       3, 0, 2, 0, 1, 2, 0, 1, 4, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 3, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 2, 0, 2, 1, 0, 0, 2,
       1, 1, 0, 3, 3, 1, 1, 2, 2, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 3, 0,
       1, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 3, 1, 0, 0, 0, 2,
       4, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0, 0, 4, 2, 3,
       0, 3, 2, 0, 1, 0], dtype=int64)

In [82]:
print(confusion_matrix(y_test,preds))

[[59 15  6  6  0]
 [17 21  9  4  3]
 [ 3 10  5  1  0]
 [ 3  3  8  5  1]
 [ 0  2  1  0  0]]


In [83]:
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           0       0.72      0.69      0.70        86
           1       0.41      0.39      0.40        54
           2       0.17      0.26      0.21        19
           3       0.31      0.25      0.28        20
           4       0.00      0.00      0.00         3

    accuracy                           0.49       182
   macro avg       0.32      0.32      0.32       182
weighted avg       0.51      0.49      0.50       182



In [84]:
pred_train=model.predict(x_train)

In [85]:
# Prediction on train datapred_train = model.predict(x_train)
print(confusion_matrix(y_train,pred_train))

[[313   0   0   0   0]
 [  0 211   0   0   0]
 [  0   0  90   0   0]
 [  0   0   0  87   0]
 [  0   0   0   0  25]]


In [86]:
print(classification_report(y_train,pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       313
           1       1.00      1.00      1.00       211
           2       1.00      1.00      1.00        90
           3       1.00      1.00      1.00        87
           4       1.00      1.00      1.00        25

    accuracy                           1.00       726
   macro avg       1.00      1.00      1.00       726
weighted avg       1.00      1.00      1.00       726

